package hw2

object Catalog {
  val data = Map(
    ("ABD", "Iran"),
    ("AEH", "Chad"),
    ("ABZ", "United Kingdom"),
    ("ABR", "USA"),
    ("ABJ", "Cote d'Ivoire"),
    ("ABI", "USA"),
    ("AUH", "United Arab Emirates"),
    ("ABV", "Nigeria"),
    ("AUE", "Egypt"),
    ("ABS", "Egypt"),
    ("ACA", "Mexico"),
    ("ACC", "Ghana"),
    ("ADA", "Turkey"),
    ("ADD", "Ethiopia"),
    ("ADL", "Australia"),
    ("ADE", "Yemen"),
    ("ADF", "Turkey"),
    ("AER", "Russia"),
    ("AJY", "Niger"),
    ("AGA", "Morocco"),
    ("SUM", "Guam"),
    ("AGZ", "South Africa"),
    ("BQN", "Puerto Rico"),
    ("AGU", "Mexico"),
    ("AMD", "India"),
    ("AYU", "Papua New Guinea"),
    ("AJA", "France"),
    ("AXT", "Japan"),
    ("CAK", "USA"),
    ("AKT", "Cyprus"),
    ("AAN", "United Arab Emirates"),
    ("AAC", "Egypt"),
    ("ALH", "Australia"),
    ("ABY", "USA"),
    ("ALB", "USA"),
    ("LBI", "France"),
    ("AAL", "Denmark"),
    ("ABQ", "USA"),
    ("ABX", "Australia"),
    ("ACI", "Channel Islands"),
    ("ALP", "Syria"),
    ("AES", "Norway"),
    ("ALJ", "South Africa"),
    ("HBH", "Egypt"),
    ("ALY", "Egypt"),
    ("ESF", "USA (LA)"),
    ("FJR", "United Arab Emirates"),
    ("AHO", "Italy"),
    ("ALG", "Algeria"),
    ("AHU", "Morocco"),
    ("ALC", "Spain"),
    ("ASP", "Australia"),
    ("ADY", "South Africa"),
    ("ABE", "USA"),
    ("ALA", "Kazakhstan"),
    ("LEI", "Spain"),
    ("ALF", "Norway"),
    ("AAT", "PR China"),
    ("ACH", "Switzerland"),
    ("AOO", "USA"),
    ("AXS", "USA"),
    ("ASJ", "Japan"),
    ("AMA", "USA"),
    ("AZB", "Papua New Guinea"),
    ("AMM", "Jordan"),
    ("ADJ", "Jordan"),
    ("ATQ", "India"),
    ("AMS", "Netherlands"),
    ("QNB", "India"),
    ("ANC", "USA"),
    ("AOI", "Italy"),
    ("ALV", "Andorra"),
    ("AXA", "Anguilla"),
    ("AJN", "Comoros (Comores)"),
    ("ANK", "Turkey"),
    ("ESB", "Turkey"),
    ("AAE", "Algeria"),
    ("ARB", "USA"),
    ("NCY", "France"),
    ("ANB", "USA"),
    ("AYT", "Turkey"),
    ("TNR", "Madagascar"),
    ("ANU", "Antigua and Barbuda"),
    ("ANR", "Belgium"),
    ("AOJ", "Japan"),
    ("APW", "Samoa"),
    ("ATW", "USA"),
    ("AQJ", "Jordan"),
    ("AJU", "Brazil"),
    ("ARH", "Russia"),
    ("ARK", "Tanzania"),
    ("GPA", "Greece"),
    ("RLT", "Niger"),
    ("ACE", "Spain"),
    ("AUA", "Aruba"),
    ("AVL", "USA"),
    ("ASB", "Turkmenistan"),
    ("ASM", "Eritrea"),
    ("ASE", "USA"),
    ("ATZ", "Egypt"),
    ("TSE", "Kazakhstan"),
    ("ASU", "Paraguay"),
    ("ASW", "Egypt"),
    ("ATH", "Greece"),
    ("HEW", "Greece"),
    ("AHN", "USA"),
    ("ATO", "USA"),
    ("ATL", "USA"),
    ("ACY", "USA"),
    ("YAT", "Canada"),
    ("AKL", "New Zealand"),
    ("AGB", "Germany"),
    ("AGS", "USA"),
    ("AUG", "USA"),
    ("AUR", "France"),
    ("AUS", "USA"),
    ("AYW", "Indonesia"),
    ("AYQ", "Australia"),
    ("AYR", "Australia"),
    ("BJZ", "Spain"),
    ("BGW", "Iraq"),
    ("IXB", "India"),
    ("NAS", "The Bahamas"),
    ("BHV", "Pakistan"),
    ("BAH", "Bahrain"),
    ("BFL", "USA"),
    ("BAK", "Azerbaijan"),
    ("BNK", "Australia"),
    ("BWI", "USA"),
    ("ABM", "Australia"),
    ("BKO", "Mali"),
    ("BBY", "Central African Republic"),
    ("BWN", "Brunei"),
    ("BDO", "Indonesia"),
    ("BLR", "India"),
    ("BGU", "Central African Republic"),
    ("DMK", "Thailand"),
    ("BKK", "Thailand"),
    ("BGR", "USA"),
    ("BGF", "Central African Republic"),
    ("BJL", "Gambia"),
    ("BNP", "Pakistan"),
    ("BCN", "Spain"),
    ("BLA", "Venezuela"),
    ("BDU", "Norway"),
    ("BRI", "Italy"),
    ("BZL", "Bangladesh"),
    ("BDQ", "India"),
    ("BRR", "United Kingdom"),
    ("BAQ", "Colombia"),
    ("BSL", "Switzerland"),
    ("EAP", "Switzerland"),
    ("BSR", "Iraq"),
    ("PTP", "Guadeloupe"),
    ("SKB", "Saint Kitts and Nevis"),
    ("BIA", "France"),
    ("BTR", "USA"),
    ("BYU", "Germany"),
    ("BPT", "USA"),
    ("BKW", "USA"),
    ("EIS", "Virgin Islands (British)"),
    ("PEK", "China"),
    ("NAY", "China"),
    ("BEW", "Mozambique"),
    ("BEY", "Lebanon"),
    ("BEL", "Brazil"),
    ("BHD", "United Kingdom"),
    ("BFS", "United Kingdom"),
    ("IXG", "India"),
    ("BEG", "Serbia"),
    ("BZE", "Belize"),
    ("BLI", "USA"),
    ("CNF", "Brazil"),
    ("BJI", "USA"),
    ("BEB", "United Kingdom"),
    ("BEN", "Libya"),
    ("BUG", "Angola"),
    ("BEH", "USA"),
    ("BBT", "Central African Republic"),
    ("BGY", "Italy"),
    ("BGO", "Norway"),
    ("EGC", "France"),
    ("BER", "Germany"),
    ("SXF", "Germany"),
    ("TXL", "Germany"),
    ("THF", "Germany"),
    ("BDA", "Bermuda"),
    ("BRN", "Switzerland"),
    ("ZDJ", "Switzerland"),
    ("BET", "USA"),
    ("BHO", "India"),
    ("BBI", "India"),
    ("BIQ", "France"),
    ("BIO", "Spain"),
    ("BIL", "USA"),
    ("BLL", "Denmark"),
    ("BTU", "Malaysia"),
    ("IRO", "Central African Republic"),
    ("BHX", "United Kingdom"),
    ("BHM", "USA"),
    ("FRU", "Kyrgyzstan"),
    ("BIS", "USA"),
    ("BXO", "Guinea-Bissau"),
    ("BLK", "United Kingdom"),
    ("BLT", "Australia"),
    ("BLZ", "Malawi"),
    ("BHE", "New Zealand"),
    ("BFN", "South Africa"),
    ("BMI", "USA"),
    ("BMG", "USA"),
    ("BLF", "USA"),
    ("BVB", "Brazil"),
    ("BOY", "Burkina Faso"),
    ("BOO", "Norway"),
    ("BJV", "Turkey"),
    ("BOG", "Colombia"),
    ("BOI", "USA"),
    ("BLQ", "Italy"),
    ("BOM", "India"),
    ("BON", "Netherlands Antilles"),
    ("YVB", "Canada"),
    ("BOB", "French Polynesia"),
    ("BOD", "France"),
    ("BXS", "USA"),
    ("BOS", "USA"),
    ("BYK", "Cote d'Ivoire"),
    ("BOJ", "Bulgaria"),
    ("BOH", "United Kingdom"),
    ("ZBO", "Australia"),
    ("BZN", "USA"),
    ("BFD", "USA"),
    ("BRD", "USA"),
    ("BMP", "Australia"),
    ("BSB", "Brazil"),
    ("BTS", "Slovakia"),
    ("BZV", "Congo"),
    ("BRE", "Germany"),
    ("VBS", "Italy"),
    ("BES", "France"),
    ("BIV", "Central African Republic"),
    ("BDR", "USA"),
    ("BGI", "Barbados"),
    ("BDS", "Italy"),
    ("BNE", "Australia"),
    ("BRS", "United Kingdom"),
    ("BNN", "Norway"),
    ("BHQ", "Australia"),
    ("BKX", "USA"),
    ("BME", "Australia"),
    ("BQK", "USA"),
    ("BRU", "Belgium"),
    ("BGA", "Colombia"),
    ("BUH", "Romania"),
    ("OTP", "Romania"),
    ("BUD", "Hungary"),
    ("BUE", "Argentina"),
    ("EZE", "Argentina"),
    ("AEP", "Argentina"),
    ("BFO", "Zimbabwe"),
    ("BUF", "USA"),
    ("BJM", "Burundi"),
    ("BUQ", "Zimbabwe"),
    ("BHC", "USA"),
    ("BDB", "Australia"),
    ("BUR", "USA"),
    ("BRL", "USA"),
    ("BTV", "USA"),
    ("BWT", "Australia"),
    ("BTM", "USA")
  )
}
