import random
from sys import argv
from datetime import datetime, timedelta
from pathlib import Path

data_path = Path(__file__).parent / "../generated-data/data.csv"
catalog_path = Path(__file__).parent / "../generated-data/catalog.csv"
rnd = random.Random()

CATALOG = (
    ("Denmark", "AAR"),
    ("Iran", "ABD"),
    ("Chad", "AEH"),
    ("United Kingdom", "ABZ"),
    ("USA", "ABR"),
    ("Cote d'Ivoire", "ABJ"),
    ("USA", "ABI"),
    ("United Arab Emirates", "AUH"),
    ("Nigeria", "ABV"),
    ("Egypt", "AUE"),
    ("Egypt", "ABS"),
    ("Mexico", "ACA"),
    ("Ghana", "ACC"),
    ("Turkey", "ADA"),
    ("Ethiopia", "ADD"),
    ("Australia", "ADL"),
    ("Yemen", "ADE"),
    ("Turkey", "ADF"),
    ("Russia", "AER"),
    ("Niger", "AJY"),
    ("Morocco", "AGA"),
    ("Guam", "SUM"),
    ("South Africa", "AGZ"),
    ("Puerto Rico", "BQN"),
    ("Mexico", "AGU"),
    ("India", "AMD"),
    ("Papua New Guinea", "AYU"),
    ("France", "AJA"),
    ("Japan", "AXT"),
    ("USA", "CAK"),
    ("Cyprus", "AKT"),
    ("United Arab Emirates", "AAN"),
    ("Egypt", "AAC"),
    ("Australia", "ALH"),
    ("USA", "ABY"),
    ("USA", "ALB"),
    ("France", "LBI"),
    ("Denmark", "AAL"),
    ("USA", "ABQ"),
    ("Australia", "ABX"),
    ("Channel Islands", "ACI"),
    ("Syria", "ALP"),
    ("Norway", "AES"),
    ("South Africa", "ALJ"),
    ("Egypt", "HBH"),
    ("Egypt", "ALY"),
    ("USA (LA)", "ESF"),
    ("United Arab Emirates", "FJR"),
    ("Italy", "AHO"),
    ("Algeria", "ALG"),
    ("Morocco", "AHU"),
    ("Spain", "ALC"),
    ("Australia", "ASP"),
    ("South Africa", "ADY"),
    ("USA", "ABE"),
    ("Kazakhstan", "ALA"),
    ("Spain", "LEI"),
    ("Norway", "ALF"),
    ("PR China", "AAT"),
    ("Switzerland", "ACH"),
    ("USA", "AOO"),
    ("USA", "AXS"),
    ("Japan", "ASJ"),
    ("USA", "AMA"),
    ("Papua New Guinea", "AZB"),
    ("Jordan", "AMM"),
    ("Jordan", "ADJ"),
    ("India", "ATQ"),
    ("Netherlands", "AMS"),
    ("India", "QNB"),
    ("USA", "ANC"),
    ("Italy", "AOI"),
    ("Andorra", "ALV"),
    ("Anguilla", "AXA"),
    ("Comoros (Comores)", "AJN"),
    ("Turkey", "ANK"),
    ("Turkey", "ESB"),
    ("Algeria", "AAE"),
    ("USA", "ARB"),
    ("France", "NCY"),
    ("USA", "ANB"),
    ("Turkey", "AYT"),
    ("Madagascar", "TNR"),
    ("Antigua and Barbuda", "ANU"),
    ("Belgium", "ANR"),
    ("Japan", "AOJ"),
    ("Samoa", "APW"),
    ("USA", "ATW"),
    ("Jordan", "AQJ"),
    ("Brazil", "AJU"),
    ("Russia", "ARH"),
    ("Tanzania", "ARK"),
    ("Greece", "GPA"),
    ("Niger", "RLT"),
    ("Spain", "ACE"),
    ("Aruba", "AUA"),
    ("USA", "AVL"),
    ("Turkmenistan", "ASB"),
    ("Eritrea", "ASM"),
    ("USA", "ASE"),
    ("Egypt", "ATZ"),
    ("Kazakhstan", "TSE"),
    ("Paraguay", "ASU"),
    ("Egypt", "ASW"),
    ("Greece", "ATH"),
    ("Greece", "HEW"),
    ("USA", "AHN"),
    ("USA", "ATO"),
    ("USA", "ATL"),
    ("USA", "ACY"),
    ("Canada", "YAT"),
    ("New Zealand", "AKL"),
    ("Germany", "AGB"),
    ("USA", "AGS"),
    ("USA", "AUG"),
    ("France", "AUR"),
    ("USA", "AUS"),
    ("Indonesia", "AYW"),
    ("Australia", "AYQ"),
    ("Australia", "AYR"),
    ("Spain", "BJZ"),
    ("Iraq", "BGW"),
    ("India", "IXB"),
    ("The Bahamas", "NAS"),
    ("Pakistan", "BHV"),
    ("Bahrain", "BAH"),
    ("USA", "BFL"),
    ("Azerbaijan", "BAK"),
    ("Australia", "BNK"),
    ("USA", "BWI"),
    ("Australia", "ABM"),
    ("Mali", "BKO"),
    ("Central African Republic", "BBY"),
    ("Brunei", "BWN"),
    ("Indonesia", "BDO"),
    ("India", "BLR"),
    ("Central African Republic", "BGU"),
    ("Thailand", "DMK"),
    ("Thailand", "BKK"),
    ("USA", "BGR"),
    ("Central African Republic", "BGF"),
    ("Gambia", "BJL"),
    ("Pakistan", "BNP"),
    ("Spain", "BCN"),
    ("Venezuela", "BLA"),
    ("Norway", "BDU"),
    ("Italy", "BRI"),
    ("Bangladesh", "BZL"),
    ("India", "BDQ"),
    ("United Kingdom", "BRR"),
    ("Colombia", "BAQ"),
    ("Switzerland", "BSL"),
    ("Switzerland", "EAP"),
    ("Iraq", "BSR"),
    ("Guadeloupe", "PTP"),
    ("Saint Kitts and Nevis", "SKB"),
    ("France", "BIA"),
    ("USA", "BTR"),
    ("Germany", "BYU"),
    ("USA", "BPT"),
    ("USA", "BKW"),
    ("Virgin Islands (British)", "EIS"),
    ("China", "PEK"),
    ("China", "NAY"),
    ("Mozambique", "BEW"),
    ("Lebanon", "BEY"),
    ("Brazil", "BEL"),
    ("United Kingdom", "BHD"),
    ("United Kingdom", "BFS"),
    ("India", "IXG"),
    ("Serbia", "BEG"),
    ("Belize", "BZE"),
    ("USA", "BLI"),
    ("Brazil", "CNF"),
    ("USA", "BJI"),
    ("United Kingdom", "BEB"),
    ("Libya", "BEN"),
    ("Angola", "BUG"),
    ("USA", "BEH"),
    ("Central African Republic", "BBT"),
    ("Italy", "BGY"),
    ("Norway", "BGO"),
    ("France", "EGC"),
    ("Germany", "BER"),
    ("Germany", "SXF"),
    ("Germany", "TXL"),
    ("Germany", "THF"),
    ("Bermuda", "BDA"),
    ("Switzerland", "BRN"),
    ("Switzerland", "ZDJ"),
    ("USA", "BET"),
    ("India", "BHO"),
    ("India", "BBI"),
    ("France", "BIQ"),
    ("Spain", "BIO"),
    ("USA", "BIL"),
    ("Denmark", "BLL"),
    ("Malaysia", "BTU"),
    ("Central African Republic", "IRO"),
    ("United Kingdom", "BHX"),
    ("USA", "BHM"),
    ("Kyrgyzstan", "FRU"),
    ("USA", "BIS"),
    ("Guinea-Bissau", "BXO"),
    ("United Kingdom", "BLK"),
    ("Australia", "BLT"),
    ("Malawi", "BLZ"),
    ("New Zealand", "BHE"),
    ("South Africa", "BFN"),
    ("USA", "BMI"),
    ("USA", "BMG"),
    ("USA", "BLF"),
    ("Brazil", "BVB"),
    ("Burkina Faso", "BOY"),
    ("Norway", "BOO"),
    ("Turkey", "BJV"),
    ("Colombia", "BOG"),
    ("USA", "BOI"),
    ("Italy", "BLQ"),
    ("India", "BOM"),
    ("Netherlands Antilles", "BON"),
    ("Canada", "YVB"),
    ("French Polynesia", "BOB"),
    ("France", "BOD"),
    ("USA", "BXS"),
    ("USA", "BOS"),
    ("Cote d'Ivoire", "BYK"),
    ("Bulgaria", "BOJ"),
    ("United Kingdom", "BOH"),
    ("Australia", "ZBO"),
    ("USA", "BZN"),
    ("USA", "BFD"),
    ("USA", "BRD"),
    ("Australia", "BMP"),
    ("Brazil", "BSB"),
    ("Slovakia", "BTS"),
    ("Congo", "BZV"),
    ("Germany", "BRE"),
    ("Italy", "VBS"),
    ("France", "BES"),
    ("Central African Republic", "BIV"),
    ("USA", "BDR"),
    ("Barbados", "BGI"),
    ("Italy", "BDS"),
    ("Australia", "BNE"),
    ("United Kingdom", "BRS"),
    ("Norway", "BNN"),
    ("Australia", "BHQ"),
    ("USA", "BKX"),
    ("Australia", "BME"),
    ("USA", "BQK"),
    ("Belgium", "BRU"),
    ("Colombia", "BGA"),
    ("Romania", "BUH"),
    ("Romania", "OTP"),
    ("Hungary", "BUD"),
    ("Argentina", "BUE"),
    ("Argentina", "EZE"),
    ("Argentina", "AEP"),
    ("Zimbabwe", "BFO"),
    ("USA", "BUF"),
    ("Burundi", "BJM"),
    ("Zimbabwe", "BUQ"),
    ("USA", "BHC"),
    ("Australia", "BDB"),
    ("USA", "BUR"),
    ("USA", "BRL"),
    ("USA", "BTV"),
    ("Australia", "BWT"),
    ("USA", "BTM"),
)

AIRPORTS = random.sample(CATALOG, k=5)

with open(data_path, 'w') as file:
    for i in range(100):
        raw_timestamp = datetime.now()
        date = raw_timestamp - timedelta(minutes=random.randint(10, 40), hours=random.randint(-2, 2))
        origin = random.choice(AIRPORTS)
        destination = random.choice(AIRPORTS)
        while origin == destination:
            destination = random.choice(AIRPORTS)
        date_string = date.strftime("%H:%M")
        file.write(f"{i},{date_string},{origin[1]},{destination[1]}\n")

with open(catalog_path, "w") as file:
    for (airport, country) in AIRPORTS:
        file.write(f"{country},{airport}\n")
